export const EVENTS = [
  {
    id: 1,
    title: "Burna Boy — Space Drift Tour",
    artist: "Burna Boy",
    genre: "Afrobeats",
    genreEmoji: "🔥",
    description: "An explosive Afrobeats headline show from Grammy Award winner Burna Boy. Expect anthems, special guests, and a night that will define 2026. No curfew. No limits.",
    longDesc: "Burna Boy brings his record-breaking Space Drift Tour to Ibadan for one night only. Fresh off multiple sold-out global dates, this show promises an immersive production — stunning visuals, a 20-piece live band, and a setlist spanning every era of his catalogue. Supporting acts TBA. This is the biggest concert Ibadan has seen in years.",
    date: "Thu, Mar 19, 2026",
    time: "9:00 PM – 2:00 AM",
    city: "Ibadan",
    venue: "Agodi Gardens Amphitheatre",
    price: 15000,
    vipPrice: 35000,
    currency: "₦",
    attending: 2400,
    capacity: 3000,
    badge: "live",
    badgeLabel: "Live Tonight",
    img: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800&q=80",
    tags: ["Afrobeats", "Live Band", "Outdoor"],
  },
  {
    id: 2,
    title: "Seun Kuti & Egypt 80 — Afrobeat Revivalist",
    artist: "Seun Kuti",
    genre: "Jazz & Soul",
    genreEmoji: "🎷",
    description: "Seun Kuti continues his father's revolutionary Afrobeat legacy. A hypnotic blend of jazz, funk, and fierce political energy in an intimate seated venue.",
    longDesc: "One of Africa's most electrifying live acts, Seun Kuti & Egypt 80 perform with a full 20-piece orchestra. The set weaves Fela's originals with Seun's own politically charged compositions — a rare, unmissable cultural event. Doors open at 7 PM. Dinner reservations available.",
    date: "Fri, Mar 20, 2026",
    time: "8:00 PM – 11:00 PM",
    city: "Ibadan",
    venue: "The Place, Jericho",
    price: 3500,
    vipPrice: 8000,
    currency: "₦",
    attending: 540,
    capacity: 800,
    badge: "soon",
    badgeLabel: "This Week",
    img: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&q=80",
    tags: ["Jazz", "Afrobeat", "Seated", "Live Band"],
  },
  {
    id: 3,
    title: "Tems × Omah Lay — Midnight Frequency",
    artist: "Tems & Omah Lay",
    genre: "R&B / Afropop",
    genreEmoji: "🌀",
    description: "Two of Africa's most magnetic voices share a stage. A dreamy, soul-drenched night of R&B-infused Afropop with a live band in tow.",
    longDesc: "For the first time on the same stage, Tems and Omah Lay deliver back-to-back headline sets before joining for a surprise collaborative finale. The Midnight Frequency show is a celebration of the new sound of Africa — emotional, cinematic, and unforgettable. Strictly limited tickets remain.",
    date: "Sat, Mar 21, 2026",
    time: "8:30 PM – 12:00 AM",
    city: "Ibadan",
    venue: "The Palms Event Centre",
    price: 12000,
    vipPrice: 25000,
    currency: "₦",
    attending: 2891,
    capacity: 3000,
    badge: "hot",
    badgeLabel: "Selling Fast",
    img: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80",
    tags: ["R&B", "Afropop", "Collab Show"],
  },
  {
    id: 4,
    title: "Underground Voices — Open Mic Night",
    artist: "Various Artists",
    genre: "Open Mic",
    genreEmoji: "🎙",
    description: "Ibadan's most vibrant open mic platform for emerging poets, singers, rappers, and spoken word artists. Come perform or witness the next big thing.",
    longDesc: "Now in its 3rd season, Underground Voices is Ibadan's premier platform for raw talent. Any genre, any style — just bring your voice. Sign up at the door to perform a 5-minute slot, or come as an audience member and be the first to discover Nigeria's next breakout stars.",
    date: "Sun, Mar 22, 2026",
    time: "7:00 PM – 10:30 PM",
    city: "Ibadan",
    venue: "Cubana, Ring Road",
    price: 0,
    vipPrice: 0,
    currency: "₦",
    attending: 180,
    capacity: 350,
    badge: "free",
    badgeLabel: "Free Entry",
    img: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80",
    tags: ["Open Mic", "Free", "Emerging Artists"],
  },
  {
    id: 5,
    title: "Adekunle Gold × Simi — Acoustic Sessions",
    artist: "Adekunle Gold & Simi",
    genre: "Highlife",
    genreEmoji: "🎵",
    description: "An intimate acoustic evening with Nigeria's most beloved musical couple. Raw, stripped-back versions of fan favourites plus new unreleased material.",
    longDesc: "An evening stripped of production excess — just two guitars, two voices, and pure emotion. Adekunle Gold and Simi perform their biggest hits in full acoustic arrangements, share stories from behind the songs, and preview tracks from their upcoming joint project. Strictly 350 seats. Book early.",
    date: "Fri, Mar 27, 2026",
    time: "7:30 PM – 10:00 PM",
    city: "Osogbo",
    venue: "Leisure Mall, Osogbo",
    price: 8500,
    vipPrice: 18000,
    currency: "₦",
    attending: 342,
    capacity: 800,
    badge: "soon",
    badgeLabel: "Upcoming",
    img: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&q=80",
    tags: ["Highlife", "Acoustic", "Intimate"],
  },
  {
    id: 6,
    title: "DJ Neptune — Amapiano Night Vol. 7",
    artist: "DJ Neptune",
    genre: "Amapiano",
    genreEmoji: "⚡",
    description: "Volume 7 of Ibadan's most consistent electronic dance night. DJ Neptune brings the log drums, the keys, and the full Amapiano experience.",
    longDesc: "The series that put Ibadan on the Amapiano map returns for its seventh edition. DJ Neptune headlines with a 3-hour back-to-back set, joined by resident DJs and surprise guest performers from the SA and Nigerian Amapiano scenes. Expect smoke machines, lasers, and a crowd that doesn't stop moving.",
    date: "Thu, Mar 19, 2026",
    time: "10:00 PM – 3:00 AM",
    city: "Ibadan",
    venue: "Amigos, UI Road",
    price: 2000,
    vipPrice: 5000,
    currency: "₦",
    attending: 410,
    capacity: 500,
    badge: "live",
    badgeLabel: "Tonight",
    img: "https://images.unsplash.com/photo-1571266752735-a9b5ed5b167c?w=800&q=80",
    tags: ["Amapiano", "DJ Set", "Club Night"],
  },
];

export const ARTISTS = [
  { id: 1, name: "Burna Boy", genre: "Afrobeats", events: 1, img: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=400&q=80", followers: "2.4M" },
  { id: 2, name: "Seun Kuti", genre: "Afrobeat / Jazz", events: 1, img: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=400&q=80", followers: "340K" },
  { id: 3, name: "Tems", genre: "R&B / Afropop", events: 1, img: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&q=80", followers: "1.8M" },
  { id: 4, name: "Adekunle Gold", genre: "Highlife / Afropop", events: 1, img: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&q=80", followers: "890K" },
  { id: 5, name: "DJ Neptune", genre: "Amapiano / Electronic", events: 1, img: "https://images.unsplash.com/photo-1571266752735-a9b5ed5b167c?w=400&q=80", followers: "620K" },
  { id: 6, name: "Omah Lay", genre: "Afropop / R&B", events: 1, img: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&q=80", followers: "1.1M" },
];

export const VENUES = [
  { id: 1, name: "Agodi Gardens Amphitheatre", city: "Ibadan", cap: 3000, events: 1, img: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&q=80", type: "Outdoor Amphitheatre" },
  { id: 2, name: "The Place, Jericho", city: "Ibadan", cap: 800, events: 1, img: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=400&q=80", type: "Indoor Venue" },
  { id: 3, name: "The Palms Event Centre", city: "Ibadan", cap: 3000, events: 1, img: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=400&q=80", type: "Multi-purpose Hall" },
  { id: 4, name: "Cubana, Ring Road", city: "Ibadan", cap: 350, events: 1, img: "https://images.unsplash.com/photo-1571266752735-a9b5ed5b167c?w=400&q=80", type: "Lounge & Bar" },
  { id: 5, name: "Leisure Mall, Osogbo", city: "Osogbo", cap: 800, events: 1, img: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&q=80", type: "Mall Venue" },
  { id: 6, name: "Amigos, UI Road", city: "Ibadan", cap: 500, events: 1, img: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&q=80", type: "Club" },
];

export const GENRES = ["All Events","Tonight","This Week","Afrobeats","Amapiano","Jazz","Highlife","Electronic","R&B / Soul","Open Mic","Free Entry"];
